template_sets:
  global-email-templates:
    label: global-email-templates
    base_path: templates
    order: 1000
    templates:
      index:
      individual:
      page:
      archive:
      custom:
      widget:
      system:

